// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxRvT_X-tyiK2cRX31jB8bpOsFvZ3WnDA',
    appId: '1:164443204817:web:4f3058d78359347b1c69f0',
    messagingSenderId: '164443204817',
    projectId: 'lighthouse-map-app',
    authDomain: 'lighthouse-map-app.firebaseapp.com',
    storageBucket: 'lighthouse-map-app.firebasestorage.app',
    measurementId: 'G-KF9C8SQSRP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJrg98WfHatN8hR0GWnrxwdjJnSnhseBk',
    appId: '1:164443204817:android:19186b18b9208e3f1c69f0',
    messagingSenderId: '164443204817',
    projectId: 'lighthouse-map-app',
    storageBucket: 'lighthouse-map-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYaVYG4IJWPBDihGYjOdzJTDSZUqO0OZs',
    appId: '1:164443204817:ios:bed2efed2e2517861c69f0',
    messagingSenderId: '164443204817',
    projectId: 'lighthouse-map-app',
    storageBucket: 'lighthouse-map-app.firebasestorage.app',
    iosBundleId: 'com.example.lighthouseMap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYaVYG4IJWPBDihGYjOdzJTDSZUqO0OZs',
    appId: '1:164443204817:ios:bed2efed2e2517861c69f0',
    messagingSenderId: '164443204817',
    projectId: 'lighthouse-map-app',
    storageBucket: 'lighthouse-map-app.firebasestorage.app',
    iosBundleId: 'com.example.lighthouseMap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxRvT_X-tyiK2cRX31jB8bpOsFvZ3WnDA',
    appId: '1:164443204817:web:0b5464f3503f093a1c69f0',
    messagingSenderId: '164443204817',
    projectId: 'lighthouse-map-app',
    authDomain: 'lighthouse-map-app.firebaseapp.com',
    storageBucket: 'lighthouse-map-app.firebasestorage.app',
    measurementId: 'G-RYDXF8Y2TR',
  );
}
